name: OpenTelemetry Export Trace

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building binary
      run: |
        echo "build build"
        
    - name: Send data to OTLP backend
      uses: codeboten/github-action-to-otlp@v1
      with:
        endpoint: ${{ secrets.ENDPOINT }}
