name: OpenTelemetry Export Trace

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Building binary
      run: |
        echo "build build"
        
    - name: Export Workflow Trace
      uses: inception-health/otel-export-trace-action@latest
      with:
        otlpEndpoint: ${{ secrets.ENDPOINT }}
        otlpHeaders: "hello=world"
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        otelServiceName: hello-otel
